### ISSUE TITLE
No SSH password set

### ISSUE THREAD

**Issue by F1LT3R** [remarkableno/linux#4]
No SSH password is being set for root over USB since doing a factory reset.

I had used the tool Remarkable Templates Installer.

https://www.einkpads.com/products/remarkable-template-installer-apple-computers

I have tried many factory resets, etc. I can not get the  SSH password in about to appear.

It just says...

```
...and you can connect using the SSH protocol using the username root' and the password ''.
```

The password appears to be blank.

I have also tried to `ssh root@192.168.x.x` and it is asking for a password.

Any ideas how I can fix this?

**Comment by sandsmark** [comment]
We neither support nor endorse third-party applications (for obvious reasons), and anything I link to below is not officially supported either, and voids warranties (to the extent allowed by applicable laws).

And this is not an official communication, see the standard Twitter bio text everyone has about this. :-)

But this is very probably because the disk is full (I don't think Remarkable Templates Installer checks for disk space or errors, so it happily fills the entire disk), so when our software tries to set a password it fails.

And for security reasons we don't allow connecting via SSH without a password.

So the solution is to either get it to boot into an older version of the OS (there was an issue with the latest release which caused it to have use way too much disk space), or manually cleaning up the root partition.

The only way to "automatically" boot the old version of the OS is to get the application to crash repeatedly during startup, so doing things manually is probably the only viable way.

The "unbricking" tool for iMX SoCs is imx_usb_loader, and our fork is available here to comply with the license of it; https://github.com/reMarkable/imx_usb_loader (there's also a link there to some unofficial documentation from another user). Once that is launched it should bring up a serial interface over USB (/dev/ttyACM0 for example), so you can connect with e. g. `cu -l /dev/ttyACM0`, log in, mount the root partition (check with fw_printenv which is the correct one), and nuke some files until there's enough space to be able to ssh in, and once you get in via ssh running journalctl --vacum-whatever is probably a good idea to free up more space.

**Comment by sandsmark** [comment]
... and closing because this is already tracked internally.

**Comment by F1LT3R** [comment]
Ok thanks. I fixed this be re-flashing the device with a tool I found on Reddit.

What is interesting to me about the reMarkable project, is that I feel there is a huge missed opportunity to engage with the community in an open way.

I love my neMarkable and use it everyday with custom templates. This has made it an invaluable tool for me.

Its been great to see how far the software quality has come.

I only wish the creators were more open and provided the community with more help and support to create more software for the remarkable, for example, a text editor that lets you use a USB keyboard would be fantastic. Or a way to start a terminal session on the eInk screen.

But one of the most valuable about the device is that it is distratcion free. (No apps). So there's a tough choice there... How can you open a platform and keep it distraction free?

**Comment by lthienard** [comment]
> 
> 
> Ok thanks. I fixed this be re-flashing the device with a tool I found on Reddit.
> 
> What is interesting to me about the reMarkable project, is that I feel there is a huge missed opportunity to engage with the community in an open way.
> 
> I love my neMarkable and use it everyday with custom templates. This has made it an invaluable tool for me.
> 
> Its been great to see how far the software quality has come.
> 
> I only wish the creators were more open and provided the community with more help and support to create more software for the remarkable, for example, a text editor that lets you use a USB keyboard would be fantastic. Or a way to start a terminal session on the eInk screen.
> 
> But one of the most valuable about the device is that it is distratcion free. (No apps). So there's a tough choice there... How can you open a platform and keep it distraction free?

Hi, i have same problem with no SSH Password, what tool do you use ? I have tested RCU but SSh Password is wrong.

Thank's for help

**Comment by Eeems** [comment]
@lthienard What reMarkable hardware do you have? rM1 or rM2?
https://remarkablewiki.com/tech/recovery_rm1
https://remarkablewiki.com/tech/recovery_rm2

**Comment by lthienard** [comment]
> 
> 
> Ok thanks. I fixed this be re-flashing the device with a tool I found on Reddit.
> 
> What is interesting to me about the reMarkable project, is that I feel there is a huge missed opportunity to engage with the community in an open way.
> 
> I love my neMarkable and use it everyday with custom templates. This has made it an invaluable tool for me.
> 
> Its been great to see how far the software quality has come.
> 
> I only wish the creators were more open and provided the community with more help and support to create more software for the remarkable, for example, a text editor that lets you use a USB keyboard would be fantastic. Or a way to start a terminal session on the eInk screen.
> 
> But one of the most valuable about the device is that it is distratcion free. (No apps). So there's a tough choice there... How can you open a platform and keep it distraction free?

Hi, i have same problem with no SSH Password, what tool do you use ? I have tested RCU but SSh Password is wrong.

Thank's for help

> 
> 
> @lthienard What reMarkable hardware do you have? rM1 or rM2? https://remarkablewiki.com/tech/recovery_rm1 https://remarkablewiki.com/tech/recovery_rm2

Sorry, rM2

**Comment by lthienard** [comment]
> 
> 
> @lthienard What reMarkable hardware do you have? rM1 or rM2? https://remarkablewiki.com/tech/recovery_rm1 https://remarkablewiki.com/tech/recovery_rm2

Ok Thank's, what linux distribution do you use ?

**Comment by Eeems** [comment]
> > @lthienard What reMarkable hardware do you have? rM1 or rM2? https://remarkablewiki.com/tech/recovery_rm1 https://remarkablewiki.com/tech/recovery_rm2
> 
> Ok Thank's, what linux distribution do you use ?

I believe most rm2 users who have gone through the process used something ubuntu based.
